spring.application.name=Restaurant
server.port=8086

#welcome.message= Welcome to Restaurant MS

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2
# Datasource
spring.datasource.username=ranim
spring.datasource.password=
spring.datasource.url=jdbc:h2:file:./Database/Data/restaurant;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto = update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


#spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false


#eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true


logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG


management.endpoint.health.show-details=always

#config server
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8887

management.endpoints.web.exposure.include=refresh,health,info


# keycloak realm config (desactive)
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/RestauBoardKeycloak
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/RestauBoardKeycloak/protocol/openid-connect/certs



# Spring RabbitMQ
spring.rabbitmq.host=localhost
#port par d�faut du protocole AMQP
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
